// web-frontend/src/app/features/articles/components/article/article-header/article-header.component.ts
import { Component, Input } from '@angular/core';
import { LanguageOptionsService } from '../../../../../shared/language/services/language-options.service';
import { ArticleFullDto } from '../../../models/Article';
import { faEye, faStar } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

@Component({
  selector: 'app-article-header',
  imports: [FontAwesomeModule],
  templateUrl: './article-header.component.html',
  styleUrl: './article-header.component.css'
})
export class ArticleHeaderComponent {
    @Input() article?: ArticleFullDto;
    languageService: LanguageOptionsService;

    constructor(
        languageService: LanguageOptionsService,
    ) {
        this.languageService = languageService;
    }


    faEye = faEye;
    faStar = faStar;
}

<div class="flex w-full space-x-4 p-6 z-20 border border-gray-300 shadow-sm rounded-md">

    <div class="flex-grow space-y-2">
        <div class="text-xl font-semibold">{{ article?.title }}</div>
        <div class="text-lg text-gray-800">{{ article?.description }}</div>

        <div class="flex items-center space-x-16 pt-4">
            <div class="flex items-center space-x-4">
                <div class="font-semibold">Language: </div>
                <img [src]="'assets/flags/' + languageService.getFlagCode(article?.language) + '.svg'" class="w-8 h-8" />
            </div>

            <div class="flex items-center space-x-4">
                <div class="font-semibold">Level: </div>
                <div>{{ article?.level }}</div>
            </div>
        </div>
    </div>

    <div class="p-2 space-y-4">
        <div class="flex items-center p-2 space-x-2 border border-gray-200 rounded-md">
            <fa-icon [icon]="faStar" class="text-gray-700"></fa-icon>
            <div class="font-semibold">{{ article?.averageRating ?? 0 }}</div>
            <div>({{ article?.numberOfRatings ?? 0 }})</div>
        </div>

        <div class="flex items-center p-2 space-x-2 border border-gray-200 rounded-md">
            <fa-icon [icon]="faEye" class="text-gray-700"></fa-icon>
            <div class="font-semibold">{{ article?.readCount ?? 0 }}</div>
        </div>
    </div>
</div>

// mobile-frontend/src/app/features/article/components/ArticleHeader.tsx
import { Image, Text, View } from "react-native";
import { useTailwind } from "tailwind-rn";
import Ionicons from 'react-native-vector-icons/Ionicons';
import { LanguageIconService } from "../../../shared/language/services/LanguageIconService";
import { ArticleFullDto } from "../models/Article";

interface ArticleHeaderProps {
    article?: ArticleFullDto;
}

const ArticleHeader: React.FC<ArticleHeaderProps> = ({
    article,
}) => {
    const tailwind = useTailwind();

    const languageIcon = LanguageIconService.getIconByLanguage(article?.language);

    return (
        <View style={tailwind("px-8 py-4 border-b border-gray-300")}>
            <Text style={tailwind("text-xl font-semibold")}>{article?.title}</Text>
            <Text style={tailwind("text-gray-800 py-2")}>{article?.description}</Text>
            <View style={tailwind("flex flex-row items-center")}>
                <Text style={tailwind("mr-2 text-lg font-semibold")}>Language: </Text>
                <Image source={languageIcon} style={{ width: 24, height: 16 }} />
                
                <Text style={tailwind("ml-12 mr-2 text-lg font-semibold")}>Level: </Text>
                <Text style={tailwind("font-semibold")}>{article?.level}</Text>
            </View>

            <View style={tailwind("flex flex-row items-center pt-4")}>
                <View style={tailwind("flex flex-row items-center w-24 px-2 py-1 mr-4 border border-gray-400 rounded-md")}>
                    <Ionicons name="star" />
                    <Text style={tailwind("mx-1 text-gray-800 font-semibold")}>{article?.averageRating ?? 0}</Text>
                    <Text>({article?.numberOfRatings ?? 0})</Text>
                </View>
                <View style={tailwind("flex flex-row items-center w-24 px-2 py-1 border border-gray-400 rounded-md")}>
                    <Ionicons name="eye" />
                    <Text style={tailwind("mx-1 text-gray-800 font-semibold")}>{article?.readCount ?? 0}</Text>
                </View>
            </View>   
        </View> 
    );
}

export default ArticleHeader;
