// mobile-frontend/src/app/features/article/components/ArticleMediumCard.tsx
import { Image, Text, View } from "react-native";
import { ArticleSearchDto } from "../models/Article";
import { useTailwind } from "tailwind-rn";
import Ionicons from 'react-native-vector-icons/Ionicons';
import { LanguageOptionsService } from "../../../shared/language/services/LanguageOptionsService";
import { LanguageIconService } from "../../../shared/language/services/LanguageIconService";

interface ArticleMediumCardProps {
    article: ArticleSearchDto;
}

const ArticleMediumCard: React.FC<ArticleMediumCardProps> = ({
    article,
}) => {
    const tailwind = useTailwind();

    const languageIcon = LanguageIconService.getIconByLanguage(article.language);

    return (
        <View style={tailwind("flex flex-row items-center my-2 px-4 py-2 bg-gray-50 border border-gray-300 rounded-md")}>
            <View style={tailwind("flex-grow flex-shrink mr-4")}>
                <Text style={tailwind("text-lg font-semibold")}>{article?.title}</Text>
                <Text style={tailwind("text-gray-800")}>{article?.description ?? ""}</Text>

                <View style={tailwind("flex flex-row items-center pt-4")}>
                    <Text style={tailwind("mr-2 font-semibold")}>Language: </Text>
                    <Image source={languageIcon} style={{ width: 24, height: 16 }} />

                    <Text style={tailwind("ml-8 font-semibold")}>Level: </Text>
                    <Text style={tailwind("font-semibold")}>{article.level}</Text>
                </View>
            </View>
            <View>
                <View style={tailwind("flex flex-row items-center w-24 px-2 py-1 mb-2 border border-gray-100 rounded-md")}>
                    <Ionicons name="star" />
                    <Text style={tailwind("mx-1 text-gray-800 font-semibold")}>{article.averageRating ?? 0}</Text>
                    <Text>({article?.numberOfRatings ?? 0})</Text>
                </View>
                <View style={tailwind("flex flex-row items-center w-24 px-2 py-1 border border-gray-100 rounded-md")}>
                    <Ionicons name="eye" />
                    <Text style={tailwind("mx-1 text-gray-800 font-semibold")}>{article?.readCount ?? 0}</Text>
                </View>
            </View>
        </View>
    );
}


export default ArticleMediumCard;

// hilbert-frontend/src/app/features/articles/components/article-medium-card/article-medium-card.component.ts
import { Component, Input } from '@angular/core';
import { ArticleSearchDto } from '../../models/Article';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { CommonModule } from '@angular/common';
import { faStar, faEye } from '@fortawesome/free-solid-svg-icons';
import { FormsModule } from '@angular/forms';
import { LanguageOptionsService } from '../../../../shared/language/services/language-options.service';

@Component({
  selector: 'app-article-medium-card',
  imports: [CommonModule, FontAwesomeModule, FormsModule],
  templateUrl: './article-medium-card.component.html',
  styleUrl: './article-medium-card.component.css'
})
export class ArticleMediumCardComponent {
    @Input() article?: ArticleSearchDto;

    faStar = faStar;
    faEye = faEye;

    languageService: LanguageOptionsService;

    constructor(
        languageService: LanguageOptionsService
    ) {
        this.languageService = languageService;
    }
}

<div class="flex w-full space-x-4 p-6 border border-gray-300 shadow-sm rounded-md">

    <div class="flex-grow w-full space-y-2">
        <div class="text-lg font-semibold">{{ article?.title }}</div>
        <div class="text-gray-800">{{ article?.description }}</div>

        <div class="flex items-center space-x-16 pt-8">
            <div class="flex items-center space-x-4">
                <div class="font-semibold">Language: </div>
                <img [src]="'assets/flags/' + languageService.getFlagCode(article?.language) + '.svg'" class="w-8 h-8" />
            </div>

            <div class="flex items-center space-x-4">
                <div class="font-semibold">Level: </div>
                <div>{{ article?.level }}</div>
            </div>
        </div>
    </div>

    <div class="p-2 space-y-4">
        <div class="flex items-center p-2 space-x-2 border border-gray-200 rounded-md">
            <fa-icon [icon]="faStar" class="text-gray-700"></fa-icon>
            <div class="font-semibold">{{ article?.averageRating ?? 0 }}</div>
            <div>({{ article?.numberOfRatings ?? 0 }})</div>
        </div>

        <div class="flex items-center p-2 space-x-2 border border-gray-200 rounded-md">
            <fa-icon [icon]="faEye" class="text-gray-700"></fa-icon>
            <div class="font-semibold">{{ article?.readCount ?? 0 }}</div>
        </div>
    </div>
</div>
